spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 671305219307-2g9g79cascre56dilfn5g7j687fl98os.apps.googleusercontent.com
            client-secret: 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